cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from . forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

djangoProjectAronBazini/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your Username',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter your Password',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your Username',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter your Email Address',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600',
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[:4]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })


def cart(request):
    return render(request, 'core/../cart/templates/cart.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome to{% endblock %}

{% block content %}
    <div class="relative overflow-hidden bg-white">
        <div class="pb-80 pt-16 sm:pb-40 sm:pt-24 lg:pb-48 lg:pt-40">
            <div class="relative mx-auto max-w-7xl px-4 sm:static sm:px-6 lg:px-8">
                <div class="sm:max-w-lg">
                    <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Best <span
                            class="text-green-700">Django</span> <br>
                        MSc.CS 23/24</h1>
                    <p class="mt-4 text-xl text-gray-500">Just being the top <span class="text-red-500">Laravel</span>
                        developer in <span class="text-green-500">Polis</span>? <br>
                        Nah, that's old news. This project is one of the many proofs that I'm not just the best Laravel
                        developer of this coders generation in our school, but also the coolest Django developer too.
                    </p>
                </div>
                <div>
                    <div class="mt-10">
                        <!-- Decorative image grid -->
                        <div aria-hidden="true"
                             class="pointer-events-none lg:absolute lg:inset-y-0 lg:mx-auto lg:w-full lg:max-w-7xl">
                            <div class="absolute transform sm:left-1/2 sm:top-0 sm:translate-x-8 lg:left-1/2 lg:top-1/2 lg:-translate-y-1/2 lg:translate-x-8">
                                <div class="flex items-center space-x-6 lg:space-x-8">
                                    <div class="grid flex-shrink-0 grid-cols-1 gap-y-6 lg:gap-y-8">
                                        <div class="h-64 w-44 overflow-hidden rounded-lg sm:opacity-0 lg:opacity-100">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw2abd3c37/images/funko/upload/71131_NBALakers_LebronJames_POP_UD_GLAM-1-WEB.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw49fc21d7/images/funko/upload/73423_WAM_MM_SODA_GLAM-1-WEB.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                    </div>
                                    <div class="grid flex-shrink-0 grid-cols-1 gap-y-6 lg:gap-y-8">
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw2497e7f2/images/funko/66658-1_C.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw77d201d0/images/funko/upload/74395_DBS_Zamasu_FW_POP_GLAM-1-WEB.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw372fda77/images/funko/65427-1_C.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                    </div>
                                    <div class="grid flex-shrink-0 grid-cols-1 gap-y-6 lg:gap-y-8">
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw055d57a0/images/funko/71911-2.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                        <div class="h-64 w-44 overflow-hidden rounded-lg">
                                            <img src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dwd595fbc5/images/funko/upload/76781_SesameStreet_ElmoOnTrike_POP_GLAM-1-T-WEB.png?sw=800&sh=800"
                                                 alt="" class="h-full w-full object-cover object-center">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a href="{% url 'item:items' %}"
                           class="inline-block rounded-md border border-transparent bg-violet-600 px-8 py-3 text-center font-medium text-white hover:bg-violet-700">Browse
                            All Items</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="bg-white">
        <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
            <h2 class="text-2xl font-bold tracking-tight text-gray-900">Recently Added</h2>

            <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">

                {% for item in items %}
                    <div class="group relative">
                        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-violet-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                            <img src="{{ item.image.url }}" alt="{{ item.name }}"
                                 class="h-full w-full object-cover object-center lg:h-full lg:w-full">
                        </div>
                        <div class="mt-4 flex justify-between">
                            <div>
                                <h3 class="text-sm text-gray-700">
                                    <a href="{% url 'item:detail' item.id %}">
                                        <span aria-hidden="true" class="absolute inset-0"></span>
                                        {{ item.name }}
                                    </a>
                                </h3>
                                <p class="mt-1 text-sm text-gray-500">{{ item.category }}</p>
                            </div>
                            <p class="text-sm font-medium text-gray-900">${{ item.price }}</p>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>


    <div class="bg-violet-200">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
                <h2 class="text-2xl font-bold text-gray-900">Categories</h2>

                <div class="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
                    {% for category in categories %}
                        <div class="group relative">
                            <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
                                <img src="{{ category.image.url }}" alt="{{ category.name }}
                                     class=" h-full w-full object-cover object-center">
                            </div>
                            <h3 class="mt-6 text-sm text-gray-500">
                                <a href="{% url 'item:items' %}?category={{ category.id }}">
                                    <span class="absolute inset-0"></span>
                                    {{ category.items.count }} items
                                </a>
                            </h3>
                            <p class="text-base font-semibold text-gray-900">{{ category.name }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/blank.html' %}

{% block title %}Log in |{% endblock %}

{% block content %}

    <section class="bg-white">
        <div class="grid grid-cols-1 lg:grid-cols-2">
            <div class="flex items-center justify-center px-4 py-10 bg-white sm:px-6 lg:px-8 sm:py-16 lg:py-24">
                <div class="xl:w-full xl:max-w-sm 2xl:max-w-md xl:mx-auto">
                    <h2 class="text-3xl font-bold leading-tight text-black sm:text-4xl">Log in to <a href="/" class="text-indigo-900">Swish Store</a></h2>
                    <p class="mt-2 text-base text-gray-600">Don’t have an account? <a href="{% url 'core:signup' %}"
                                                                                      title=""
                                                                                      class="font-medium text-blue-600 transition-all duration-200 hover:text-blue-700 hover:underline focus:text-blue-700">Sign
                        up here</a></p>

                    <form method="post" action="." class="mt-4">
                        {% csrf_token %}
                        <div class="space-y-5">
                            <div>
                                <label for="" class="text-base font-medium text-gray-900"> Username </label>
                                <div class="mt-2.5">
                                    {{ form.username }}
                                </div>
                            </div>

                            <div>
                                <div class="flex items-center justify-between">
                                    <label for="" class="text-base font-medium text-gray-900"> Password </label>
                                </div>
                                <div class="mt-2.5">
                                    {{ form.password }}
                                </div>
                            </div>

                            {% if form.errors or form.non_field_errors %}
                                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}

                                    {{ form.non_field_errors }}

                                </div>
                            {% endif %}

                            <div>
                                <button type="submit"
                                        class="inline-flex items-center justify-center w-full px-4 py-4 text-base font-semibold text-white transition-all duration-200 bg-violet-600 border border-transparent rounded-md focus:outline-none hover:bg-violet-700 focus:bg-violet-700">
                                    Log in
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="flex items-center justify-center px-4 py-10 sm:py-16 lg:py-24 bg-yellow-300 sm:px-6 lg:px-8">
                <div>
                    <img class="w-full mx-auto"
                         src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dw20edd63c/images/funko/upload/60926a_POPAnimation_Naruto_RasenshurikenGW_GLAM-WEB%20-%20Copy.png?sw=800&sh=800"
                         alt="POP! NARUTO"/>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/blank.html' %}

{% block title %}Sign up |{% endblock %}

{% block content %}

    <section class="bg-white">
        <div class="grid grid-cols-1 lg:grid-cols-2">
            <div class="flex items-center justify-center px-4 py-10 bg-pink-300 sm:px-6 lg:px-8 sm:py-16 lg:py-24">
                <div>
                    <img class="w-full mx-auto"
                         src="https://funko.com/dw/image/v2/BGTS_PRD/on/demandware.static/-/Sites-funko-master-catalog/default/dwda598d78/images/funko/upload/76944_POPAnimation_DBS_Goku(Rose-BLK)(GW)_GLAM-WEB.png?sw=800&sh=800"
                         alt="POP! GOKU"/>
                </div>
            </div>

            <div class="flex items-center justify-center px-4 py-10 bg-white sm:py-16 lg:py-24 sm:px-6 lg:px-8">

                <div class="xl:w-full xl:max-w-sm 2xl:max-w-md xl:mx-auto">
                    <h2 class="text-3xl font-bold leading-tight text-black sm:text-4xl">Sign up to <a href="/" class="text-indigo-900">Swish Store</a></h2>
                    <p class="mt-2 text-base text-gray-600">Already have an account? <a href="{% url 'core:login' %}"
                                                                                        title=""
                                                                                        class="font-medium text-blue-600 transition-all duration-200 hover:text-blue-700 hover:underline focus:text-blue-700">Log
                        in here</a></p>

                    <form method="post" action="." class="mt-4">
                        {% csrf_token %}
                        <div class="space-y-5">
                            <div>
                                <label for="" class="text-base font-medium text-gray-900"> Username </label>
                                <div class="mt-2.5">
                                    {{ form.username }}
                                </div>
                            </div>

                            <div>
                                <div class="flex items-center justify-between">
                                    <label for="" class="text-base font-medium text-gray-900"> Email </label>
                                </div>
                                <div class="mt-2.5">
                                    {{ form.email }}
                                </div>
                            </div>

                        <div>
                                <div class="flex items-center justify-between">
                                    <label for="" class="text-base font-medium text-gray-900"> Email </label>
                                </div>
                                <div class="mt-2.5">
                                    {{ form.password1 }}
                                </div>
                            </div>

                        <div>
                                <div class="flex items-center justify-between">
                                    <label for="" class="text-base font-medium text-gray-900"> Email </label>
                                </div>
                                <div class="mt-2.5">
                                    {{ form.password2 }}
                                </div>
                            </div>

                            {% if form.errors or form.non_field_errors %}
                                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}

                                    {{ form.non_field_errors }}

                                </div>
                            {% endif %}

                            <div>
                                <button type="submit"
                                        class="inline-flex items-center justify-center w-full px-4 py-4 text-base font-semibold text-white transition-all duration-200 bg-violet-600 border border-transparent rounded-md focus:outline-none hover:bg-violet-700 focus:bg-violet-700">
                                    Sign up
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}