cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

djangoProjectAronBazini/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='item_category', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = ''


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),

            'name': forms.TextInput(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'description': forms.Textarea(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'price': forms.TextInput(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'image': forms.FileInput(attrs={
                'class': 'rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50'
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'description': forms.Textarea(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'price': forms.TextInput(attrs={
                'class': 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
            }),
            'image': forms.FileInput(attrs={
                'class': 'rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50'
            }),
            'is_sold': forms.CheckboxInput(attrs={
                'class': 'h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-600'
            })
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(category__name__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:4]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.pk)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Add a new item'
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.pk)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item'
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}

    <section class="relative ">
        <div class="w-full mx-auto px-4 sm:px-6 lg:px-0">
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-16 mx-auto max-md:px-2 ">
                <div class="img">
                    <div class="img-box h-full max-lg:mx-auto ">
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="max-lg:mx-auto lg:ml-auto h-full">
                    </div>
                </div>
                <div class="data w-full lg:pr-8 pr-0 xl:justify-start justify-center flex items-center max-lg:pb-10 xl:my-2 lg:my-5 my-0">
                    <div class="data w-full max-w-xl">
                        <p class="text-lg font-medium leading-8 text-indigo-600 mb-4">{{ item.category }}</p>
                        <h2 class="font-manrope font-bold text-3xl leading-10 text-gray-900 mb-2 capitalize">{{ item.name }}</h2>
                        <div class="flex flex-col sm:flex-row sm:items-center mb-6">
                            <h6 class="font-manrope font-semibold text-2xl leading-9 text-gray-900 pr-5 sm:border-r border-gray-200 mr-5">
                                ${{ item.price }}</h6>
                            <div class="flex items-center gap-2">
                                <p><strong class="text-indigo-600">Provider: </strong></p>
                                <span class="pl-2 font-normal leading-7 text-gray-500 text-sm ">{{ item.created_by.username }}</span>
                            </div>
                        </div>
                        <p class="text-gray-500 text-base font-normal mb-5">{{ item.description }}</p>

                        {% if request.user == item.created_by %}

                            <p>You posted this item so only you have permission to edit its content or just simply
                                delete it!</p>

                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 py-8">
                                <div class="flex sm:items-center sm:justify-center w-full">
                                    <button class="group py-4 px-5 rounded-full bg-yellow-400 text-gray-600 font-semibold text-lg w-full flex items-center justify-center gap-2 transition-all duration-500 hover:bg-yellow-300">
                                        <a href="{% url 'item:edit' item.id %}">Edit Item</a>
                                    </button>
                                </div>
                                <button class="group py-4 px-5 rounded-full bg-red-500 text-white font-semibold text-lg w-full flex items-center justify-center gap-2 transition-all duration-500 hover:bg-red-400">
                                    <a href="{% url 'item:delete' item.id %}">Delete Item</a>
                                </button>
                            </div>

                        {% else %}
                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 py-8">
                                <div class="flex sm:items-center sm:justify-center w-full">
                                    <button class="group py-4 px-6 border border-gray-400 rounded-l-full bg-white transition-all duration-300 hover:bg-gray-50 hover:shadow-sm hover:shadow-gray-300">
                                        <svg class="stroke-gray-900 group-hover:stroke-black" width="22" height="22"
                                             viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M16.5 11H5.5" stroke="" stroke-width="1.6" stroke-linecap="round"/>
                                            <path d="M16.5 11H5.5" stroke="" stroke-opacity="0.2" stroke-width="1.6"
                                                  stroke-linecap="round"/>
                                            <path d="M16.5 11H5.5" stroke="" stroke-opacity="0.2" stroke-width="1.6"
                                                  stroke-linecap="round"/>
                                        </svg>
                                    </button>
                                    <input type="text"
                                           class="font-semibold text-gray-900 cursor-pointer text-lg py-[13px] px-6 w-full sm:max-w-[118px] outline-0 border-y border-gray-400 bg-transparent placeholder:text-gray-900 text-center hover:bg-gray-50"
                                           placeholder="0">
                                    <button class="group py-4 px-6 border border-gray-400 rounded-r-full bg-white transition-all duration-300 hover:bg-gray-50 hover:shadow-sm hover:shadow-gray-300">
                                        <svg class="stroke-gray-900 group-hover:stroke-black" width="22" height="22"
                                             viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M11 5.5V16.5M16.5 11H5.5" stroke="#9CA3AF" stroke-width="1.6"
                                                  stroke-linecap="round"/>
                                            <path d="M11 5.5V16.5M16.5 11H5.5" stroke="black" stroke-opacity="0.2"
                                                  stroke-width="1.6" stroke-linecap="round"/>
                                            <path d="M11 5.5V16.5M16.5 11H5.5" stroke="black" stroke-opacity="0.2"
                                                  stroke-width="1.6" stroke-linecap="round"/>
                                        </svg>
                                    </button>
                                </div>
                                <button value="{{ item.id }}"
                                        class="group py-4 px-5 rounded-full bg-indigo-50 text-indigo-600 font-semibold text-lg w-full flex items-center justify-center gap-2 transition-all duration-500 hover:bg-indigo-100 add-cart">
                                    <svg class="stroke-indigo-600 " width="22" height="22" viewBox="0 0 22 22"
                                         fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path
                                                d="M10.7394 17.875C10.7394 18.6344 10.1062 19.25 9.32511 19.25C8.54402 19.25 7.91083 18.6344 7.91083 17.875M16.3965 17.875C16.3965 18.6344 15.7633 19.25 14.9823 19.25C14.2012 19.25 13.568 18.6344 13.568 17.875M4.1394 5.5L5.46568 12.5908C5.73339 14.0221 5.86724 14.7377 6.37649 15.1605C6.88573 15.5833 7.61377 15.5833 9.06984 15.5833H15.2379C16.6941 15.5833 17.4222 15.5833 17.9314 15.1605C18.4407 14.7376 18.5745 14.0219 18.8421 12.5906L19.3564 9.84059C19.7324 7.82973 19.9203 6.8243 19.3705 6.16215C18.8207 5.5 17.7979 5.5 15.7522 5.5H4.1394ZM4.1394 5.5L3.66797 2.75"
                                                stroke="" stroke-width="1.6" stroke-linecap="round"/>
                                    </svg>
                                    Add to cart
                                </button>

                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="bg-white">
        <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
            <h2 class="text-2xl font-bold tracking-tight text-gray-900">Similar Items</h2>

            <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">

                {% for item in related_items %}
                    <div class="group relative">
                        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-violet-200 lg:aspect-none group-hover:opacity-75 lg:h-80">
                            <img src="{{ item.image.url }}" alt="{{ item.name }}"
                                 class="h-full w-full object-cover object-center lg:h-full lg:w-full">
                        </div>
                        <div class="mt-4 flex justify-between">
                            <div>
                                <h3 class="text-sm text-gray-700">
                                    <a href="{% url 'item:detail' item.id %}">
                                        <span aria-hidden="true" class="absolute inset-0"></span>
                                        {{ item.name }}
                                    </a>
                                </h3>
                                <p class="mt-1 text-sm text-gray-500">{{ item.category }}</p>
                            </div>
                            <p class="text-sm font-medium text-gray-900">${{ item.price }}</p>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <script>
        $(document).on('click', '.add-cart', function (e) {
            e.preventDefault();
            var item_id = $(this).val();
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:add' %}',
                data: {
                    item_id: item_id,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },

                success: function (json) {
                    document.getElementById('cart_quantity').textContent =json.quantity
                },
                error: function (xhr, errmsg, err) {

                }

            });
        })
    </script>


{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

    <section class="flex justify-center relative">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="mb-6 text-3xl">{{ title }}</h1>

            <div class="space-y-4">
                {{ form.as_p }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}

                </div>
            {% endif %}

            <div class="mt-6 flex items-center justify-end gap-x-6">
                <button class="rounded-md bg-violet-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    Submit
                </button>
            </div>

        </form>
    </section>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}All Items |{% endblock %}

{% block content %}
    <div class="pd-6 grid grid-cols-4 gap-4 bg-violet-200">
        <div class="col-span-1">
            <div class="relative mt-20 rounded-md">
                <form method="get" action="{% url 'item:items' %}" class="px-2 py-3 font-medium">
                    <input name="query" type="text" value="{{ query }}"
                           class="block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                           placeholder="Search for POPs, Tees or Sodas">
                    <div class="absolute inset-y-0 right-0 flex items-center">
                        <label for="currency" class="sr-only">Search</label>
                        {% if query == "" %}
                            <button class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-indigo-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">
                                Search
                            </button>
                        {% else %}
                            <button class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-indigo-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">
                                <a href="{% url 'item:items' %}">Clear</a>
                            </button>
                        {% endif %}
                    </div>
                </form>
            </div>

            <hr>

            <h3 class="sr-only">Categories</h3>
            <ul role="list" class="px-2 py-3 font-medium text-gray-600">
                {% for category in categories %}
                    <li class="{% if category.id == category_id %} bg-violet-300 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}"
                           class="block px-2 py-3">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <ul class="px-2 font-medium">
                <li>
                    <a href="{% url 'item:items' %}"
                       class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-indigo-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">Clear
                        filters</a>
                </li>
            </ul>
        </div>

        <div class="col-span-3">

            <div class="bg-white">
                <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
                    <h2 class="sr-only">Items</h2>


                    {% if items %}
                        <div class="grid grid-cols-1 gap-x-6 gap-y-20 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                            {% for item in items %}
                                <a href="{% url 'item:detail' item.id %}" class="group">
                                    <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-violet-200 xl:aspect-h-8 xl:aspect-w-7">
                                        <img src="{{ item.image.url }}"
                                             alt="{{ item.name }}"
                                             class="h-full w-full object-cover object-center group-hover:opacity-75">
                                    </div>
                                    <h3 class="mt-4 text-sm text-gray-700">{{ item.name }}</h3>
                                    <p class="mt-1 text-lg font-medium text-gray-900">${{ item.price }}</p>
                                </a>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p class="text-lg text-gray-700">Apologies, but we couldn't find any results matching your
                            search criteria. <br>
                            Please double-check your search terms or explore our
                            other offerings.</p>
                        <br>
                        <a href="{% url 'item:items' %}"
                           class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-indigo-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">Go
                            back to browsing all our items</a>
                        <br>
                        <br>
                        <a href="/"
                           class="h-full rounded-md border-0 bg-transparent py-0 pl-2 pr-7 text-indigo-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm">Return
                            to the Homepage</a>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}